<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<ul class="easyui-tree" lines="true">
	<li><span>订单管理</span>
	<ul>
			<li><a 
				href="admin/order/index">订单列表</a></li>
			<li><a
				href="admin/order/add">添加订单</a></li>
		</ul></li>
	<li><span>单据管理</span>
	<ul>
			<li><a
				href="admin/collectiondoc/index">收款单</a></li>
			<li><a
				href="admin/refundmentdoc/index">退款单</a></li>
			<li><a
				href="admin/deliverydoc/index">配货单</a></li>
			<li><a
				href="admin/returnsdoc/index">退货单</a></li>
			<li><a
				href="admin/refundmentdoc/list">退款申请列表</a></li>
		</ul></li>
	<li><span>快递单管理</span>
	<ul>
			<li><a
				href="admin/merchshipinfo/index">发货信息管理</a></li>
		</ul></li>
</ul>